### ISSUE TITLE
Describe

### ISSUE THREAD

**Issue by cdekok** [Benestar/asparagus#18]
It would be nice if there was describe support, am currently looking what would be the best place to put it.
perhaps we can add a type var in the query builder when call ->describe() instead of ->select() 
which determines what it returns on a ->format()

**Comment by Benestar** [comment]
That sound's like a good idea. We could store it like the uniqueness constraint in a local variable and then use it in the formatter. I will try to work on this :-)

**Comment by cdekok** [comment]
Ah I just added something myself not sure if this is what you had in mind, but i needed this today ;)

**Comment by Benestar** [comment]
Released as `0.4`
