### ISSUE TITLE
Order of filter in union

### ISSUE THREAD

**Issue by cdekok** [Benestar/asparagus#23]
I have the following query:

``` php
        $query = $q->selectDistinct('?label')
            ->where('?subject', 'skos:prefLabel', '?label')
            ->union(
                $q->newSubgraph()->where('?subject', 'skos:prefLabel', '?label'),
                $q->newSubgraph()->where('?subject', 'skos:altLabel', '?label')
            )
            ->filter('regex(str(?label), ' . $eTerm . ', "i")');
```

Now i would expect the filter to be added after the union:

```
PREFIX skos: <http://www.w3.org/2004/02/skos/core#> 
SELECT DISTINCT ?label WHERE { 
  { 
    ?subject skos:prefLabel ?label .  
  }
  UNION {
  ?subject skos:altLabel ?label .  
 }
 FILTER (regex(str(?label), "radi")) .
} 
LIMIT 20 OFFSET 0
```

But what it seems currently it is always added after the select what i get is:

```
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
SELECT DISTINCT ?label WHERE {
    ?subject skos:prefLabel ?label .
    FILTER (regex (str (?label), "^radi", "i")) {
        ?subject skos:prefLabel ?label .
    } UNION {
        ?subject skos:altLabel ?label .
    }
}
```

**Comment by cdekok** [comment]
This was invalid when i remove the select it works fine the order didn't seem to matter

**Comment by Benestar** [comment]
In SPARQL the order shouldn't matter so it is the same if you put the `FILTER` before or after the `UNTION`. As those sequences get stored separately, it is currently not possible to preserve the order and I'm not sure if this is really needed.

However, what do you mean with "when i remove the select it works fine"?

**Comment by cdekok** [comment]
Yes you are correct I closed the issue already ;) It was my mistake i created a select with the union and got no results.
I thought the order had something to do with it, It should had been:

``` php
$query = $q->selectDistinct('?label')
            ->union(
                $q->newSubgraph()->where('?subject', 'skos:prefLabel', '?label'),
                $q->newSubgraph()->where('?subject', 'skos:altLabel', '?label')
            )
            ->filter('regex(str(?label), ' . $eTerm . ', "i")');
```

So i removed the

``` php
 ->where('?subject', 'skos:prefLabel', '?label')
```

Then it worked fine with the filter on top.

**Comment by Benestar** [comment]
Ah, I see. Cool it works now :+1:
