### ISSUE TITLE
Optional with filter

### ISSUE THREAD

**Issue by cdekok** [Benestar/asparagus#24]
It would be nice if the api allowed an easy way to add a filter on a optional clause.
perhaps a fourth parameter with filter could be added?
So a query like https://jena.apache.org/tutorials/sparql_optionals.html#optionals-with-filters could be created.

**Comment by cdekok** [comment]
Ah just found out this was already possible, perhaps add it to the README.md ?

``` php
$filter = new \Asparagus\GraphBuilder(new \Asparagus\UsageValidator);
$filter->where('?uri', 'skos:altLabel', '?altLabel')
                ->filter("lang (?altLabel) = 'nl' || lang (?altLabel) = 'en' || lang (?altLabel) = 'fr'");
$qb->optional($filter);
```

**Comment by Benestar** [comment]
Hmm, the way you did this is not the way it should be done ;-) GraphBuilder instances should not be created outside of this component, see also [here](https://github.com/Benestar/asparagus/blob/master/src/GraphBuilder.php#L65).

However, there is a nice way to get `GraphBuilder` instances with the right `UsageValidator` assigned already by using `QueryBuilder::newSubgraph`. This way you can also add filters to optional clauses, as in one of the [integration tests](https://github.com/Benestar/asparagus/blob/master/tests/integration/WDQSQueryExamplesTest.php#L88).

The example query can be created in the following way:

``` php
use Asparagus\QueryBuilder;

$prefixes = array(
    'info' => 'http://somewhere/peopleInfo#',
    'vcard' => 'http://www.w3.org/2001/vcard-rdf/3.0#'
);

$queryBuilder = new QueryBuilder( $prefixes );
$queryBuilder->select( '?name', '?age' )
    ->where( '?person', 'vcard:FN', '?name' )
    ->optional(
        $queryBuilder->newSubgraph()
            ->where( '?person', 'info:age', '?age' )
            ->filter( '?age > 24' )
    );

echo $queryBuilder->format();
```

I may add a note to the README that `QueryBuilde::optional` can also take a `GraphBuilder` instance.

**Comment by cdekok** [comment]
Ah thanks for the explanation I will use it this way :+1:
